version: "3.3"

services:

  activemq-central-node1:
    image: webcenter/activemq:latest
    ports:
      # mqtt
      - "1883:1881"
      # amqp
      - "5674:5672"
      # ui
      - "8163:8161"
      # stomp
      - "63613:61613"
      # ws
      - "63614:61614"
      # jms
      - "63616:61616"
    networks:
      activemq-network:
        ipv4_address: 172.28.0.2
    volumes:
      - ./conf:/opt/activemq/conf
      - ../data:/data/activemq
      - ./log:/var/log/activemq
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_QUEUES: openmrs.sync.queue
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

networks:
  activemq-network:
    external:
      name: activemq-network
